from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    BOOK_ACTIVITY_API_URL: str
    BOOK_EXCURSION_API_URL: str
    BOOK_FLIGHT_API_URL: str
    BOOK_TRIP_API_URL: str
    CANCEL_BOOKING_API_URL: str
    CANCEL_TRIP_API_URL: str
    CHANGE_FLIGHT_API_URL: str
    CHANGE_SEAT_API_URL: str
    CHANGE_TRIP_API_URL: str
    CHECK_ARRIVAL_TIME_API_URL: str
    CHECK_DEPARTURE_TIME_API_URL: str
    CHECK_EXCURSION_AVAILABILITY_API_URL: str
    CHECK_FLIGHT_AVAILABILITY_AND_FARE_API_URL: str
    CHECK_FLIGHT_AVAILABILITY_API_URL: str
    CHECK_FLIGHT_CHECKIN_STATUS_API_URL: str
    CHECK_FLIGHT_OFFERS_API_URL: str
    CHECK_FLIGHT_PRICES_API_URL: str
    CHECK_FLIGHT_RESERVATION_API_URL: str
    CHECK_FLIGHT_STATUS_API_URL: str
    CHECK_IN_API_URL: str
    CHECK_IN_PASSENGER_API_URL: str
    CHECK_REFUND_ELIGIBILITY_API_URL: str
    CHECK_SEAT_AVAILABILITY_API_URL: str
    CHECK_TRIP_DETAILS_API_URL: str
    CHECK_TRIP_OFFERS_API_URL: str
    CHECK_TRIP_PLAN_API_URL: str
    CHECK_TRIP_PRICES_API_URL: str
    CHOOSE_SEAT_API_URL: str
    CONFIRM_FLIGHT_CHANGE_API_URL: str
    ESCALATE_TO_HUMAN_AGENT_API_URL: str
    GET_AIRLINE_CHECKIN_BAGGAGE_INFO_API_URL: str
    GET_BOARDING_PASS_API_URL: str
    GET_BOARDING_PASS_PDF_API_URL: str
    GET_BOOKING_DETAILS_API_URL: str
    GET_CHECK_IN_INFO_API_URL: str
    GET_EXCURSION_CANCELLATION_POLICY_API_URL: str
    GET_FLIGHT_STATUS_API_URL: str
    GET_PHONE_CHECKIN_INFO_API_URL: str
    GET_REFUND_API_URL: str
    GET_TRIP_CANCELLATION_POLICY_API_URL: str
    GET_TRIP_SEGMENTS_API_URL: str
    INITIATE_REFUND_API_URL: str
    ISSUE_TRAVEL_CREDIT_VOUCHER_API_URL: str
    ISSUE_TRAVEL_VOUCHER_API_URL: str
    PURCHASE_FLIGHT_INSURANCE_API_URL: str
    PURCHASE_TRIP_INSURANCE_API_URL: str
    QUERY_AIRPORT_CHECKIN_INFO_API_URL: str
    QUERY_BOOKING_DETAILS_API_URL: str
    QUERY_COMPENSATION_ELIGIBILITY_API_URL: str
    QUERY_FLIGHT_AVAILABILITY_API_URL: str
    RESEND_BOARDING_PASS_API_URL: str
    RETRIEVE_BOOKING_BY_EMAIL_API_URL: str
    RETRIEVE_FLIGHT_INSURANCE_API_URL: str
    SCHEDULE_CALLBACK_API_URL: str
    SEARCH_FLIGHTS_API_URL: str
    SEARCH_FLIGHT_API_URL: str
    SEARCH_FLIGHT_PRICES_API_URL: str
    SEARCH_TRIP_API_URL: str
    SEARCH_TRIP_PRICES_API_URL: str
    SEND_BOARDING_PASS_EMAIL_API_URL: str
    SEND_EMAIL_API_URL: str
    SEND_ITINERARY_EMAIL_API_URL: str
    UPDATE_FLIGHT_DATE_API_URL: str
    UPDATE_REFUND_METHOD_API_URL: str
    VERIFY_BOOKING_AND_GET_BOARDING_PASS_API_URL: str

    INTENT_API_URL: str
    SENTIMENT_API_URL: str
    RAG_API_URL: str
    NON_AI_API_URL: str
    REDIS_HOST: str
    REDIS_PORT: str
    BEDROCK_REGION: str
    BEDROCK_MODEL_ID: str

    # Optional for STS
    AWS_PROFILE: str = ""
    ASSUME_ROLE_ARN: str = ""

    class Config:
        env_file = ".env"
        extra = "allow"  # Accept unmodeled fields without failing

settings = Settings()
